# Generated by Django 3.1.5 on 2021-01-30 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charger_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('channel_name', models.CharField(blank=True, max_length=50)),
                ('ip_adress', models.GenericIPAddressField(null=True)),
                ('version_ocpp', models.CharField(blank=True, max_length=5)),
                ('available', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaction', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('action_name', models.CharField(max_length=50)),
                ('propierties', models.JSONField(null=True)),
                ('error', models.JSONField(null=True)),
                ('type_transaction', models.BooleanField(default=False)),
                ('charger', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Controller.charger_client')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
