# Generated by Django 3.1.5 on 2021-01-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='charger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Controller.charger_client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
